// var net = require('net');

// var hCount = 0;
// var connIDs = 0;
// var cHeartBeats = {};

// var server = net.createServer(function(c) { //'connection' listener
//   console.log('server connected');

//   c.id = connIDs++;
//   cHeartBeats[c.id] = true;

//   c.on('data', function(data)
//   {
//   	console.log('Receiving: ', data.toString());
//   })
//   c.on('end', function() {
//    	cHeartBeats[c.id] = false;
//     console.log('server disconnected');
//   });
  
//   setInterval(function()
//   {
//   	if(cHeartBeats[c.id])
//   		c.write('honk check ' + (hCount++) + '\r\n');
//   }, 2000)

//   // c.pipe(c);
  
// });

// server.listen(8001, function() { //'listening' listener
//   console.log('server bound');
// });

var controlApp = require('express')();

var uiSocketServer = require(__dirname + "/UI/uiServer.js")();

var httpServer = uiSocketServer.httpServer;
var expressApp = uiSocketServer.expressApp;

controlApp.get('/doofus', function(req,res)
{

  res.json({fancy: "town"});

});

//pass control into our express app generated by the UI
expressApp.use(controlApp);


httpServer.listen('8000', function()
{

  console.log('Logged a few monkeys in my time: 8000');

})







 

